export const TYPES = {
  FACTORY: 'FACTORY',
  CONTROLLER: 'CONTROLLER'
};
export const SUB_TYPES = {
  EXTERNAL: 'EXTERNAL',
  INLINE: 'INLINE',
  EXTERNAL_DI: 'EXTERNAL_DI',
  INLINE_DI: 'INLINE_DI'
};
